FROM docker.1ms.run/hiyouga/verl:ngc-th2.6.0-cu126-vllm0.8.4-flashinfer0.2.2-cxx11abi0

COPY ./scripts/tuna-apt.sh ./scripts/tuna-apt.sh
ENV DEBIAN_FRONTEND=noninteractive
RUN bash ./scripts/tuna-apt.sh 20.04

COPY ./scripts/install-miniconda.sh ./scripts/install-miniconda.sh

# Install Miniconda if not present
RUN if ! command -v conda &> /dev/null; then \
    echo "conda not found, installing miniconda"; \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p /root/miniconda3 && \
    rm /tmp/miniconda.sh && \
    export PATH="/root/miniconda3/bin:$PATH" && \
    wget https://veml.tos-cn-beijing.volces.com/condarc -O ~/.condarc && \
    pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple && \
    conda init bash; \
    fi

# Install python if not installed
RUN if ! command -v python &> /dev/null; then \
    echo "python not found, installing python3.11"; \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11; \
    apt-get install -y python3-setuptools; \
    fi

# Install Poetry if not installed
RUN if ! command -v poetry &> /dev/null; then \
    echo "poetry not found, installing poetry"; \
    python3 --version; \
    curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.7.0 python3 - && \
    export PATH=~/.local/bin:$PATH; \
    fi

ENV PATH="/root/miniconda3/bin:${PATH}"
ENV PATH=/root/.local/bin:$PATH

# rust
# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# ENV PATH="/root/.cargo/bin:${PATH}"
# RUN rustup default stable 

# go
# COPY ./runtime/go ./runtime/go
# RUN wget https://go.dev/dl/go1.25.1.linux-amd64.tar.gz -O /tmp/go1.25.1.linux-amd64.tar.gz && \
#     tar -C /usr/local -xzf /tmp/go1.25.1.linux-amd64.tar.gz && \
#     rm /tmp/go1.25.1.linux-amd64.tar.gz
# ENV PATH="/usr/local/go/bin:${PATH}"

RUN bash ./scripts/tuna-apt.sh 20.04 \
    && apt-get update && apt-get install -y curl npm git nano wget vim unzip sudo cgroup-tools iproute2 \
    # iverilog build deps
    autoconf gperf flex bison \
    # bash scripting utils
    bc \
    && mkdir -p /workspace/download

# golang 1.23.3
RUN curl -o /workspace/download/go.tar.gz -SL https://go.dev/dl/go1.23.3.linux-amd64.tar.gz \
    && tar -zxf /workspace/download/go.tar.gz -C /usr/local && rm /workspace/download/go.tar.gz
ENV PATH=/bin:/usr/local/go/bin:$PATH

# nodejs 20.11.0
RUN curl -o /workspace/download/node.tar.gz -SL https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.gz \
    && mkdir -p /usr/local/lib/nodejs && tar -zxf /workspace/download/node.tar.gz -C /usr/local/lib/nodejs && mv /usr/local/lib/nodejs/node-v20.11.0-linux-x64 /usr/local/lib/nodejs/node \
    && rm /workspace/download/node.tar.gz
ENV PATH=/usr/local/lib/nodejs/node/bin:$PATH
ENV NODE_PATH=/usr/local/lib/node_modules
RUN npm install -g typescript@5.3.3 tsx@4.7.1

# gcc 9
RUN apt-get update && apt-get install -y build-essential g++ libboost-dev

RUN curl -o /workspace/download/openssl.tar.gz -SL https://www.openssl.org/source/old/3.0/openssl-3.0.11.tar.gz \
    && tar -zxf /workspace/download/openssl.tar.gz && cd openssl-3.0.11 && ./Configure && make && make install \
    && rm /workspace/download/openssl.tar.gz && cd .. && rm -r openssl-3.0.11
ENV PATH=/usr/bin/openssl:$PATH

# jdk 21
RUN curl -o /workspace/download/jdk.tar.gz -SL https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz \
    && mkdir /usr/java && tar -zxf /workspace/download/jdk.tar.gz -C /usr/java && rm /workspace/download/jdk.tar.gz \
    && java_path=`ls /usr/java/${path}` && echo "export JAVA_HOME=/usr/java/${java_path}" >> ~/.profile

# dotnet 8.0
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y dotnet-sdk-8.0

# php 7.4.3
RUN apt-get install -y php-cli=2:7.4+75

# rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.76.0
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup default stable 

# R, lua, ruby, julia, perl, scala
RUN apt-get install -y aptitude
RUN aptitude install -y r-base 
RUN aptitude install -y ruby-full 
RUN aptitude install -y julia 
RUN aptitude install -y scala
RUN aptitude install -y lua5.2 
RUN apt-get install -y --allow-downgrades libreadline8=8.0-4 libreadline-dev
RUN aptitude install -y liblua5.2-dev luarocks && luarocks --help
RUN luarocks install luasocket \
    && luarocks install luaunit \
    && PERL_MM_USE_DEFAULT=1 cpan Test::Deep Data::Compare

# D
RUN wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list \
    && apt-get update --allow-insecure-repositories -y \
    && apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring \
    && apt-get update && apt-get install -y dmd-compiler dub

# kotlin
RUN curl -o /tmp/kotlin-compiler.zip -SL https://github.com/JetBrains/kotlin/releases/download/v2.0.0/kotlin-compiler-2.0.0.zip \
    && mkdir /usr/local/kotlin && unzip /tmp/kotlin-compiler.zip -d /usr/local/kotlin \
    && rm -f /tmp/kotlin-compiler.zip
ENV PATH=/usr/local/kotlin/kotlinc/bin:$PATH

# iverilog && verilog-eval (TODO: remove verilog-eval)
RUN cd /workspace \
    && git clone https://github.com/steveicarus/iverilog.git && cd iverilog \
    && git checkout 01441687235135d1c12eeef920f75d97995da333 \
    && sh ./autoconf.sh && ./configure && make -j4 \
    && make install \
    && cd /workspace \
    && git clone https://github.com/NVlabs/verilog-eval \
    && cd verilog-eval && git checkout 4b9b16e92f1d9cc520afbfa3ecd5a2f20a350fd5 \
    && sed -i '79d;112d' ./verilog_eval/execution.py \
    && cd ../ && pip install -e verilog-eval

# lean 4
RUN curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:v4.10.0-rc2
ENV PATH=/root/.elan/bin:$PATH

# Racket
RUN apt-get update --allow-insecure-repositories -y && apt-get install -y racket

# Swift
RUN curl -o /workspace/download/swift.tar.gz -SL https://download.swift.org/swift-5.10.1-release/ubuntu2004/swift-5.10.1-RELEASE/swift-5.10.1-RELEASE-ubuntu20.04.tar.gz \
    && cd /workspace/download \
    && tar zxf swift.tar.gz \
    && mkdir /usr/local/swift \
    && mv swift-5.10.1-RELEASE-ubuntu20.04/usr/* /usr/local/swift \
    && rm -f /workspace/download/swift.tar.gz            
ENV PATH=/usr/local/swift/bin:$PATH

SHELL ["sh", "-lc"]
RUN update-alternatives --install /usr/bin/java java $JAVA_HOME/bin/java 20000 \
    && update-alternatives --install /usr/bin/javac javac $JAVA_HOME/bin/javac 20000 \
    && rm -r /workspace/download \
    && env

COPY ./runtime/go ./runtime/go
# download and cache go deps
RUN cd ./runtime/go \
    && go env -w GOPROXY="https://goproxy.cn|direct" \
    && go build

COPY ./runtime/node /root/sandbox/runtime/node
# also install puppetter chrome requirements (TODO: keep effective packages only)
# install nodejs
RUN wget -qO- https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    node -v && npm -v

# cache dotnet
RUN dotnet new console -o /tmp/dotnet && dotnet run --project /tmp/dotnet

# cache lean
ENV PATH="/root/.elan/bin:${PATH}"
COPY ./runtime/lean /root/sandbox/runtime/lean
RUN export && cd /root/sandbox/runtime/lean && lake build

COPY ./runtime/python ./runtime/python
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
# RUN cd ./runtime/python && bash install-python-runtime.sh

RUN rm -f ~/.condarc
RUN conda create -n sandbox-runtime -y python=3.11
RUN source activate sandbox-runtime

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN cd ./runtime/python \ 
    && source activate sandbox-runtime \ 
    && pip install -r ./requirements.txt --ignore-requires-python \
    && python -c "import nltk; nltk.download('punkt')" \
    && python -c "import nltk; nltk.download('stopwords')" \
    && conda clean --all -y

# fix pyqt error, see https://github.com/NVlabs/instant-ngp/discussions/300
ENV QT_QPA_PLATFORM=offscreen
ENV OMP_NUM_THREADS=2

COPY ./ /root/sandbox
WORKDIR /root/sandbox
RUN poetry config virtualenvs.create false \
    && touch /root/miniconda3/pyvenv.cfg \
    && conda create -n sandbox -y python=3.12 \
    && conda init bash

# Make RUN commands use the new conda environment:
SHELL ["conda", "run", "-n", "sandbox", "/bin/bash", "-c"]

RUN poetry install

RUN apt install -y nginx
RUN conda config --set auto_activate False
